spring:
  application:
    name: demo_authentication

  datasource:
    url: jdbc:mysql://localhost:3306/cookdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false

logging:
  level:
    org:
      springframework:
        security:
          web: trace
        transaction:
          interceptor: trace
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

